title: Trayvonious Pendleton
email: trayvoniouspendleton@gmail.com
description: >-
  Data Scientist, Software Engineer, and Financial Modeling Enthusiast.

baseurl: "" # Do not change for user site
url: "https://trayp20.github.io"
theme: jekyll-theme-architect

show_downloads: false